### ISSUE TITLE
Issue Running Script

### ISSUE THREAD

**Issue by MJCyberCitizen** [hornerit/powershell#2]
Below is what I am running, am I doing something wrong?

powershell.exe -executionpolicy bypass -file "C:\Temp\Powershell\Exchange.ps1"                    Please enter an Exchange Admin email address: admin@domain.com.au

Name
----
company.onmicrosoft.com
Exception calling "Load" with "1" argument(s): "Failed to create a 'End' from the text '15/11/2021'."
At C:\Temp\Powershell\Exchange.ps1:280 char:9
+         $Window = [Windows.Markup.XamlReader]::Load($Reader)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : XamlParseException

You cannot call a method on a null-valued expression.
At C:\Temp\Powershell\Exchange.ps1:286 char:17
+ ...             Set-Variable -Name $_.Name -Value $window.FindName($_.Nam ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by hornerit** [comment]
I realize that this is long overdue and I'm so sorry, I didn't have an alert or anything indicating that an error appeared. I believe the issue is due to localized formatting of the dateTime. My regional settings are MM/DD/YYYY so I think the GUI is failing to load because it's trying to black out dates in a calendar picker from 1/1/1200 to (today + 3 days)...but I think XAML might be requiring the End of the blackout dates to be the en-US regional formatting. You can try to strip out the Blackout date lines and logic (219-221, 269-271, and 282-284) and everything else I've tried to use UTC so that we avoid regional/cultural issues.
